# This is a basic workflow to help you get started with Actions

name: Mirror and run Gitlab CI on pull requests and push

# Controls when the action will run. 
on: [push, pull_request]
#on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  ## Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: PR and Push testing on external Gitlab
        uses: adityakavalur/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/aditya.kavalur/target-repo.git"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "aditya.kavalur"
          #The below password is really a PAT, needs write
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD_ALL }}
          GITLAB_PROJECT_ID: "23147442"
          #The below password is really a PAT, needs read
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POLL_TIMEOUT: "120"
